### ISSUE TITLE
Question How to load additional module required for tests

### ISSUE THREAD

**Issue by MK-2001** [ioBroker/testing#309]
Hello, 

I am using the default test from https://github.com/ioBroker/create-adapter.

With it I get an erring during the test, that a required module from 7pm of my Adapter could not be found. 

How I can add an additional module for your tests?

My Repo is there: https://github.com/MK-2001/ioBroker.go-e

**Comment by Apollon77** [comment]
Do you have a link to such a broken testing?

**Comment by MK-2001** [comment]
Like that: https://travis-ci.com/github/MK-2001/ioBroker.go-echarger/builds/175656151 ?

**Comment by Apollon77** [comment]
@AlCalzone Error: Cannot find module 'axios'

**Comment by AlCalzone** [comment]
🤔 
![grafik](https://user-images.githubusercontent.com/17641229/87633865-76018e00-c73c-11ea-8f99-a9a8e893048c.png)

**Comment by AlCalzone** [comment]
Why do you load axios in the integration test file and not use it?
https://github.com/MK-2001/ioBroker.go-e/blob/decde81fc7a1b8a85f9bb7c95db886020d879844/test/integration.js

**Comment by AlCalzone** [comment]
Also, your `.travis.yml` is nonstandard. It should look like this:
```yml
os:
  - linux
  - osx
  - windows
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
env:
  - CXX=g++-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
before_install:
  - 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then CC=gcc-6; fi'
  - 'if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then CC=g++-6; fi'
before_script:
  - export NPMVERSION=$(echo "$($(which npm) -v)"|cut -c1)
  - 'if [[ $NPMVERSION == 5 ]]; then npm install -g npm; fi'
  - npm -v
script:
  - npm run test:package
  - npm run test:unit
  - export DEBUG=testing:*
  - npm run test:integration
```
